### ISSUE TITLE
Should organization type say 'agent name'?

### ISSUE THREAD

**Issue by nicolevasilevsky** [NLightenGroup/nlighten-ontology#12]
Shouldn't it say 'organization name'?

![image](https://user-images.githubusercontent.com/6722114/33783645-745c88b0-dc12-11e7-93a3-cf5e82fb6869.png)

**Comment by marijane** [comment]
This is when you create an organization?  How do you get to this screen?  I don't know how to tell where it might be getting "Agent" from.

"Agent" is defined as the range for copyrightHolder (because I assumed a union wouldn't work based on the screenshots from yesterday) and it is the superclass for Organization and Person.

**Comment by nicolevasilevsky** [comment]
1. From here: https://alaska.dev.eagle-i.net/sweet
2. Click Create an organization
3. On this page, you can see agent name, agent type

**Comment by nicolevasilevsky** [comment]
Ah, if agent is the superclass for org or person, that explains why it is being displayed here. I am not sure if we should allow person as an option here, we didn't do that in eagle-i.

**Comment by marijane** [comment]
I agree, if you're clicking "create an organization", person shouldn't be here.  I'm not sure what change needs to be made in the ontology, though, to fix this, because I'm not sure how it got here in the first place.

Is there a different place to create people?  I want people to be createable instances so we can associate creators with their courses.

**Comment by nicolevasilevsky** [comment]
Yes, in eagle-i, people would be created in a different record. I think they always had to be associated with an org or a resource though, you couldn't just create a stand-alone person record.

**Comment by skcheng** [comment]
Yes, I think people can only be created as part of another resource. In our case, when creating a course, we should be able to click in the drop down next to creator and have an option to add new. This would create a stub for the person that can then be completed in the next step.

I'm wondering if part of the other issue with people is maybe we need another relationship besides creator? In the blink & eagle-i ontologies I think the relationships are things like provided_by, director_of, etc. See: https://search.eagle-i.net/model/#t=http://xmlns.com/foaf/0.1/Person&of=score.

Maybe creator is being reserved as metadata for creator of the record, e.g. whoever is entering the data. Does this ring any bells?

**Comment by pitviper6** [comment]
I think in regular old eagle-i, it's just person. we can add a title if we
like but there aren't people sub classes. And yes, you have to create a
person as a stub in an organization record.

**Comment by pitviper6** [comment]
Oh wait, but yes, there are classes of people! You create the stub as a PI,
Director, contact person or other member. So for education resources,
perhaps you'd want instructor and creator roles?

**Comment by marijane** [comment]
The domain/range constraint additions on "provider" seems to have fixed this:
![screen shot 2017-12-12 at 1 49 38 pm](https://user-images.githubusercontent.com/1771847/33910374-68af2926-df43-11e7-9477-629bdb4f48fb.png)
