### ISSUE TITLE
problem with creator field

### ISSUE THREAD

**Issue by nicolevasilevsky** [NLightenGroup/nlighten-ontology#23]
When I try to create a new resource, and add a provider, the provider link is not clickable. It should link to a new person record (or other person records in the repo).

![image](https://user-images.githubusercontent.com/6722114/33790603-7989c4fa-dc36-11e7-80fa-12c5d5869a5f.png)

Note, the audience dropdown works properly, so the creator should be set up the same way, I think.

**Comment by skcheng** [comment]
I feel like I already said this somewhere, but I can't remember if I really did or just thought about it:

Without digging into the code, and just from what I'm seeing by behavior, I'm going to guess the specific term `dc:creator` is used to represent the person creating the record and the application relegates this term to being a metadata and the application doesn't allow for direct editing of metadata.

In which case, this is intended behavior and no longer an issue since #15 removes a bunch of the extraneous fields.

**Comment by marijane** [comment]
Now that I've been through the process of creating a resource, it seems to me that these values default to the current organization.  The question is why.  One theory, it's using the range of the properties to figure out it's an organization and uses the current org as default.  Another theory, this is something related to being in the Primary property group.

**Comment by skcheng** [comment]
This is because of the ResourceProvider annotation on creator & contributor.  I've removed these annotations locally and it appears to be fixed locally:
![screen shot 2017-12-12 at 5 08 17 pm](https://user-images.githubusercontent.com/1533193/33911075-11d20ad0-df5f-11e7-8b45-47feba3adf13.png)
