### ISSUE TITLE
children of resource format are not loaded in software

### ISSUE THREAD

**Issue by nicolevasilevsky** [NLightenGroup/nlighten-ontology#24]
there are no options in the dropdown for resource format on the [create new resource page](https://alaska.dev.eagle-i.net/sweet/#history?stubView=false&initResourcesView=false&referencesView=false&mode=edit&typeUri=http://schema.org/CreativeWork&typeLabel=Educational%20Resource&providerUri=http://alaska.dev.eagle-i.net/i/00000160-38b6-1720-3878-376d80000000&providerLabel=Testing2&filterProviderUri=http://alaska.dev.eagle-i.net/i/00000160-38b6-1720-3878-376d80000000&filterProviderLabel=Testing2&filterTypeUri=http://schema.org/CreativeWork&filterTypeLabel=Educational%20Resource)

![image](https://user-images.githubusercontent.com/6722114/33790712-60e99924-dc37-11e7-9cdc-6e59704360df.png)

**Comment by skcheng** [comment]
@nicolevasilevsky Here's a blast from the past. I'm not sure if you remember there was this weird bug in eagle-i that was inconsistent and hard to reproduce ... the bug is when the drop down box for the ontology automagically jumps and shows up in random places on the screen instead of where you clicked. Notably, it seemed to show up at the top left on the browser a lot.

![image](https://user-images.githubusercontent.com/1533193/33799051-1316e33a-dcf2-11e7-8877-9204c272eea5.png)
