### ISSUE TITLE
<none> property is showing up on all records

### ISSUE THREAD

**Issue by nicolevasilevsky** [NLightenGroup/nlighten-ontology#44]
I imagine you are probably already aware of this, but there is a <none> property showing up on all records.

**Comment by marijane** [comment]
I would love to know where this is coming from!

**Comment by marijane** [comment]
I am going to scour the application layer for references to removed properties, I could see that being a cause of this behavior.

@skcheng, is there a way to find out what property the software thinks this is?

**Comment by skcheng** [comment]
@marijane Something is pulling in `http://purl.org/dc/elements/1.1/license` as a property for `http://schema.org/CreativeWork`... does that help narrow things down? I think that `http://purl.org/dc/elements/1.1/license` is no longer a valid term maybe? And that's why it's coming back with no label, definition or range.

**Comment by marijane** [comment]
This is super weird.  http://purl.org/dc/elements/1.1/license does not appear anywhere in the main ontology or the application layer.  It seems to be getting imported by the IAO ontology.  I haven't used it anywhere, either, removed or otherwise.

Is this a situation like foaf:Organization, where the application expects it to be used somehow?

**Comment by marijane** [comment]
I put a DataModelExclude annotation on dc:license.  Not sure if it will work but it seems worth a try.

**Comment by marijane** [comment]
it totally worked
