### ISSUE TITLE
 Reconsider some properties

### ISSUE THREAD

**Issue by nicolevasilevsky** [NLightenGroup/nlighten-ontology#55]
MJ asked me to review the current properties.
On the educational resource, here are my suggestions:

- has domain - should have a different label (add a preferred label), as I feel like this is more of an ontology term, not as user friendly. Maybe consider 'subject area' instead?
- has audience - consider preferred label - intended audience
- has creator - consider preferred label - created by or could be author(s)
- has depth - not sure what this means (see #50)
- has duration - I understand what this means, but I don't think it is super intuitive. Maybe give it a preferred label of 'Course or Video duration' or just 'Duration'
- has format - not sure what this means 
- identifier - not sure what this means, is this meant to be like a DOI or something like that? There is also the same as field at the bottom. Or could be a course ID like BIO 101? Maybe give it a preferred label of "Resource Identifier"? and give it a tool tip.
- learning resource type - not sure what this means
- license - seems fine
- time required - this should be grouped with has duration
(I noticed these are currently appearing in alphabetical order, which may not be the best display)

Additional properties you may want to consider:
I guess some other questions would be about the type of resources being added - are they all going to be online resources somehow, or would they be a course that is offered during some specific time period? 
- If yes, then we should include when the course will be offered (like winter term, Jan - Mar 2018).
- instructor - we have creator and contributor, but we don't necessarily know who the instructor(s) is/are
- consider including 'development date' (the date when the resource was created)

**Comment by marijane** [comment]
Thank you for this excellent feedback, Nicole!  Lots of good suggestions.

To answer some questions:
"has depth" refers to how detailed the resources are, i.e., introductory vs advanced.  I borrowed this model from https://bioportal.bioontology.org/ontologies/DSEO/?p=classes&conceptid=root which is the knowledge map ontology for https://bigdatau.ini.usc.edu/explore_erudite, but I notice now they use a different label in their web app.  similar story with has domain and has format.

"identifier" is a field from schema.org and yes, it's intended to be used for a unique identifier. 
When I decided to pull it in it was sort of a "sure, why not?" kind of thing.
http://schema.org/identifier

learning resource type is also from schema.org.  http://schema.org/learningResourceType

**Comment by marijane** [comment]
Tagging #42 because it's related to this one.

**Comment by marijane** [comment]
I'm thinking about better labels and I need to think out loud for a bit here.

* **has domain**: I'm really struggling with this label.  I picked "Domain" after Carolyn Jones suggested avoiding the word "Competency".  The label I like best is "Clinical Research Competency" but I'm not certain that users will understand that.  "Subject Area" feels a bit too broad.
* **has audience**  - I like the suggestion of "Intended Audience" here and will be implementing this.
* **has creator**  - I like "Created By" here.
* **has depth** - Currently considering "Training Level" for this label.
* **has duration** - I like "Video Duration" here.
* **has format** - This may be redundant.  The resources themselves are Courses or Videos, and while the format taxonomy has more detail than the CreativeWork hierarchy, I'm not really sure its necessary.
* **identifier** - I'm going to refactor this, per #57.
* **learning resource type** - Probably going to remove this because it is also sort of redundant.  The definition is "_The predominant type or kind characterizing the learning resource. For example, 'presentation', 'handout'._" Schema.org likes to give users more than one way to model things and this might be an example of that.

Other thoughts:
* As far as I know, everything in NLighten is going to be an online resource.
* I like the idea of adding instructor.
* I also like the idea of adding a creation date.
