### ISSUE TITLE
do we need has part and is part of?

### ISSUE THREAD

**Issue by nicolevasilevsky** [NLightenGroup/nlighten-ontology#60]
What is the difference between these two properties? Do we need both of them?

**Comment by marijane** [comment]
They're inverses of each other.  has part goes from the whole to the part, and is part of goes from the part to the whole.  for example, body has part head vs head is part of body.

**Comment by nicolevasilevsky** [comment]
do we want both properties on the same record though?

**Comment by marijane** [comment]
Hmm, maybe not.  Right now both the domain and range are schema:CreativeWork (educational resource), which is why they show up on both, and that would have to be changed, which probably means adding additional educational resource classes.

A part of a Course might be a Course Module.  I'll go look for terms to pull in, and also remind myself what the Common Cartridge spec calls these things.

A Video might be part of a Course, maybe a Playlist.

**Comment by marijane** [comment]
I am going to hold off on trying to implement different domains/ranges for these properties right now.  It may become clearer what's needed after we get some real content uploaded.

**Comment by marijane** [comment]
I'm not seeing a need to act on this ticket right now.
