### ISSUE TITLE
Empty drop-downs for same-organization values

### ISSUE THREAD

**Issue by marijane** [NLightenGroup/nlighten-ontology#64]
If I create a new resource in an organization that already has resources, the drop-down values for properties like "Intended Audience" are empty until you click the link to show properties from all organizations.

**Comment by marijane** [comment]
I wonder if this will work ok with an empty data repository...?

**Comment by skcheng** [comment]
@marijane This is expected behavior. Because Audience is currently a resource type and not a referenced thing. All resources must belong to an organization. An Audience created under the organization Harvard Catalyst would mean that the Audience belongs to Harvard Catalyst. When we are referencing an object that is not a referenced object, the default behavior is to restrict to the resources for that organization and it is intended that choosing a resource from another organization is an additional step. For example, a flow cytometer instrument is created for the organization Harvard Catalyst. When I create a service and I want to reference the flow cytometer, I am most likely going to want to reference the flow cytometer at my organization, and not the flow cytometer at OHSU. This seems to further support that Audience should probably be a referenced object and not an instance create, see issue 67/

@nicolevasilevsky I'm not sure if the correct term is 'referenced taxonomy' for what the Audience should be instead of instance create. Do you know what it should be referred to? Pun slightly intended.

**Comment by marijane** [comment]
I think what I need is a type of resource that users can create because they're not known by the ontology in advance and that everyone can use.  Not sure if that exists in eagle-i.  Oh wait, @skcheng, is this what the http://eagle-i.org/ont/app/1.0/ClassGroup_Global annotation is for?

**Comment by skcheng** [comment]
@marijane If I understand you correctly, you're looking for something analogous to a manufacturer for an instrument. When you're creating a new instrument and are adding the manufacturer value, you have an option of selecting a manufacturer from 'Commonly Used' list or a manufacturer that belongs to the current organization.

And in this analogy, what you are looking for is to have a list of audiences under 'Commonly Used' that is shared across all of the organizations and a list of audiences that belong to the current organization.

If that is the case, then we need to add this request as a 2.0 feature request. The annotation ClassGroup_Global indicates that the property might have a list of commonly used resources. This tells the application 2 things:
* For SWEET, contact the global server and get all of the manufacturers and provide them as an option under 'Commonly Used Resources'
* For search, excludes them from search results

For now, the work around you are doing now is sufficient (extra step). If we were working with more than one node, this would be more of a blocker because the two nodes can't share references to the same resource. I.e. alaska used to have its own instance of a mouse and ohsu had its own instance of a mouse, even though they both just wanted to refer to the same singluar generic mouse. This was one of the impetus for creating this global repository thing.
