### ISSUE TITLE
Researchers Quick Search link has no search results

### ISSUE THREAD

**Issue by marijane** [NLightenGroup/nlighten-ontology#90]
See
https://alaska.dev.eagle-i.net:8443/institution/#inst?uri=http://alaska.dev.eagle-i.net/i/00000160-74d0-537e-ceb9-6dad80000000

I have seen resources that have Researcher as an audience, I don't think this is supposed to be empty.

**Comment by skcheng** [comment]
No, this is not a bug. This record legitimately does not have any other information associated to it besides it's type and name.

I think this goes back to whether or not Audience should be it's own type or a referenced taxonomy. If it is its own type/instance/record, this is how they look because there aren't many properties associated to it.

**Comment by marijane** [comment]
Oh, so it's linking to the record for Researchers?  I expected it to link to search results for resources targeted at Researcher audiences, similar to how the other quick searches work.
